version: "3"
services:
  bootstrap:
    container_name: bootstrap
    build: "./bootstrap"
    image: localethereum/pyethapp-bootstrap
    restart: always
    networks:
      back:
          ipv4_address: 172.18.250.2
  miner:
    container_name: miner
    build: "./miner"
    image: localethereum/pyethapp-miner
    environment:
      - BOOTSTRAP_NODE=enode://d3260a710a752b926bb3328ebe29bfb568e4fb3b4c7ff59450738661113fb21f5efbdf42904c706a9f152275890840345a5bc990745919eeb2dfc2c481d778ee@172.18.250.2:30303
      - MINE_PERCENT=50
      - SLEEPTIME=1
    restart: always
    networks:
      back:
          ipv4_address: 172.18.250.4
networks:
  back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.18.250.0/24
